---
# @author Anthony Loukinas <anthony.loukinas@redhat.com>

version: '3'

services:
  web:
    image: registry.redhat.io/ansible-tower-37/ansible-tower-rhel7
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - '80:8052'
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - ./assets/SECRET_KEY:/etc/tower/SECRET_KEY
      - ./assets/environment.sh:/etc/tower/conf.d/environment.sh
      - ./assets/credentials.py:/etc/tower/conf.d/credentials.py
      - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets/redis_socket:/var/run/redis/:rw
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  task:
    image: registry.redhat.io/ansible-tower-37/ansible-tower-rhel7
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - ./assets/SECRET_KEY:/etc/tower/SECRET_KEY
      - ./assets/environment.sh:/etc/tower/conf.d/environment.sh
      - ./assets/credentials.py:/etc/tower/conf.d/credentials.py
      - ./assets/redis_socket:/var/run/redis/:rw
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./assets/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./assets/redis_socket:/var/run/redis/:rw

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - awx-postgres-db:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      http_proxy:
      https_proxy:
      no_proxy:

volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
  awx-postgres-db: