---
version: '3'

services:

  web:
    image: registry.redhat.io/ansible-tower-37/ansible-tower-rhel7
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./assets/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./assets/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./assets/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./assets/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./assets/redis_socket:/var/run/redis/:rw"

  task:
    image: registry.redhat.io/ansible-tower-37/ansible-tower-rhel7
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./assets/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./assets/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./assets/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./assets/redis_socket:/var/run/redis/:rw"
    environment:
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: registry.redhat.io/rhscl/redis-5-rhel7:latest
    container_name: awx_redis
    restart: unless-stopped
    command: ["/etc/redis.conf"]
    volumes:
      - "./assets/redis.conf:/etc/redis.conf:ro"
      - "./assets/redis_socket:/var/run/redis/:rw"

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - awx_db:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx

volumes:
  awx_db:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
