name: Run Test Playbooks AWX Devel

on: [push, pull_request]

jobs:
  Integration-test:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: "Build AWX stack"
        run: cd .github/docker && docker-compose up -d

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: "Install dependencies"
        run: pip install -r .github/requirements.txt

      - name: Display Versions
        run: which python && pip --version && ansible --version

      - name: "List all running containers"
        run: docker ps -a

      - name: "Wait for awx to be alive"
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:80/api/v2/ping'
          responseCode: 200
          timeout: 600000  # Wait max 10 mins for response
          interval: 3000

      - name: "Install Galaxy dependencies"
        run: ansible-galaxy collection install -r .github/collections/requirements_awx_devel.yml

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '20s'

      - name: "Perform playbook tests"
        run: ansible-playbook playbooks/configure_tower.yml -e tower_hostname=http://localhost:80 -e tower_username=admin -e tower_password=password

      - name: "Perform export model playbook tests"
        run: ansible-playbook playbooks/configure_tower_export_model.yml -e tower_hostname=http://localhost:80 -e tower_username=admin -e tower_password=password
